name: Sync to Hugging Face Space

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true # Crucial for your .pt and .keras files

      - name: Push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # Connecting GitHub to your specific HF Space
          git remote add space https://Lord731095:$HF_TOKEN@huggingface.co/spaces/Lord731095/accidentSeverity-api
          git push --force space main
